dependencies:
  - conda-forge::cmake
  - conda-forge::compilers
  - defaults::numpy
  - defaults::scipy
  - conda-forge::h5py
  - conda-forge::hdf5
  - python
  - pip
  - pip:
    - pyscf
    - line_profiler
    - pytest
